### ISSUE TITLE
[Code Review] Suggested improvements/changes

### ISSUE THREAD

**Issue by OstlerDev** [lilchicky/uvx_magic_mirror#1]
Hey lilchicky!

I love the idea of the project! It would be really useful to have a proper place to see when the bus will arrive. I figured opening up an "issue" would be the best way to communicate about the changes. This is purely trying to be constructive feedback 😸 

The code looks great and to be honest there really wasn't functionality that I saw that needed to be changed. Most of the improvements that could be made are purely in clarity of your code. Working these strategies into your current and future code will really take your coding to the next level.

## Expand Readme
1. Add instructions to `README.md` for how the program can be run and any files needed to run. For example, if there is an `index.html` file you are using, or some commands you are using to run the application, include it as instructions. I wasn't quite sure how to run the application, so I wasn't actually able to test if it worked
2. From a little research it seems like it might be related to the "MagicMirror" open source "smart mirror" project. It would be cool to include some of those details in the readme to help explain more about what the project is for

## Code Clarity
1. Add code comments. Right before/after you write a chunk of code add a comment explaining what that chunk of code does. Writing down your thoughts as you go as comments will really help take your coding to the next level.
2. Attempt to reuse as much of the code as you can, and add named variables to add clarity to your functions and if statements, this makes it easier for other engineers to come along and read it later.
3. Add functions for frequently repeated chunks of code to help reuse as much as you can. For example, I added the `getNextStopText` helper function in the code changes below.

## Refactored code changes
Here are some of the changes I suggested in the Code Clarity section to help provide an example of the improvements, and how they produce more readable code.

I extracted the common logic from the `updateDisplay` function into a new function named `getNextStop`. The `getNextStop` function significantly simplifies the `updateDisplay` function and reuses a good bit of the code. In addition it helps us to "segment" the code into clearer more understandable chunks. Hopefully by taking a look at the refactored code you can see how splitting up bits of your code to named variables makes it much clearer what is going on.

```javascript
getNextStopText: function(nextStop) {
  return "Next Stop:\n" + times[x] + "\nHolidays may change service!";
},

getNextStop: function(times, current_hour, current_minute, nextStopText) {
  const lastStopIndex = times.length - 1;
  for(let x = 0; x < times.length; x++) {
    // Get stop for comparison
    const stop = times[x]
    const stopHour = stop.split(":")[0];
    const stopMinute = stop.split(":")[1];

    // Grab the next stop
    const nextStop = times[x + 1]
    const nextStopHour = nextStop ? nextStop.split(":")[0] : null;

    // Check to see if we are the right hour
    if (stopHour === current_hour) {
      // Check if the stop has happened yet or not, if it hasn't display it
      if (current_minute < stopMinute) {
        return this.getNextStopText(stop);
      }
      // Check to see if the next stop happens in the next hour instead of this one, if so return the next stop
      else if (x < lastStopIndex && nextStopHour !== current_hour) {
        return this.getNextStopText(nextStop);
      }
      // If we are the very last stop in the timetable then return it
      else if (x >= lastStopIndex) {
        return this.getNextStopText(times[0]);
      }
    }
    // If it isn't the right hour and we are at the end of the stops, 
    // then there isn't a stop for the rest of the day
    else if (x >= lastStopIndex) {
      return nextStopText;
    }
  }
  return null;
},

updateDisplay: function() {
  const weekTimes = [ /* week times array */ ];
  const satTimes = [ /* sat times array */ ];

  const current_hour = moment().hour();
  const current_minute = moment().minute();
  const current_day = moment().day();

  if (day === 0) {
    return "No Bus Service\non Sunday!";
  }
  else if (day === 6) {
    const nextStopText = current_hour <= 6 
        ? this.getNextStopText(satTimes[0]) 
        : "No Service Until Monday!";
    return this.getNextStop(satTimes, current_hour, current_minute, nextStopText);
  }
  else {
    const nextStopText = day === 5 && current_hour > 4
        ? this.getNextStopText(satTimes[0]) 
        : this.getNextStopText(weekTimes[0]);
    return this.getNextStop(weekTimes, current_hour, current_minute, nextStopText);
  }

  return "Next Stop:\nError";
},
```

Hope that helps!
- Sky Young 😸

**Comment by lilchicky** [comment]
Implemented a chunk of the changes in here, mostly code clarity and creating functions for repeated code.
